name: cicd.yml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  call-test-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/tests.yml

      - name: setup environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: pypi upload
        run: |
          uv build


