name: cicd.yml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  call-test-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/tests.yml


  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: Set up .pypirc
        run: |
          echo "[pypi]" > ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = ${{ secrets.PYPI_API_TOKEN }}" >> ~/.pypirc

      - name: setup environment
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: build stage
        run: |
          uv build

      - name: publish on pypi
        run: |
          uv run python3 -m twine upload dist/*
